// Exception handling
#include <iostream>
#include <string>
using namespace std;

class fun1
{
};

int main()
{
    cout << "Welcome" << endl;

// try
//     {
//        throw '1';       
//     }
    
//try
    {
       throw 10;
    }
// catch (int a)
//     {
//         cout << "int vaala ho gaya";
//     }
//     catch (char a)
//     {
//         cout << "int vaala ho gaya";
//     }

    
}